### PR TITLE
Better efficiency for logs table generation

### PR DESCRIPTION
**Pull request by Flynsarmy**
This package currently checks the DB and does a little extra work on first write every time a new instance of `WordPressHandler` is created. The process could be made a little more efficient by allowing wordpress developers to do the following with a plugin:

```php
require __DIR__.'/vendor/autoload.php';

// Create the logs table if it doesn't already exist on plugin activation
function register_activation_hook(__FILE__, function() {
    global $wpdb;

    $handler = new \WordPressHandler\WordPressHandler(
        $wpdb, "logs",
        [],
        \Monolog\Logger::DEBUG
    );

    $record = ['extra' => []];
    $handler->initialize($record);
});

// Now somewhere else in my plugin where I want to use the logger
$logger = new \Monolog\Logger('channel');
$handler = new \WordPressHandler\WordPressHandler(
    $wpdb, "logs",
    [],
    \Monolog\Logger::DEBUG
);
$handler->initialized = true; // Don't do any extra work - we've already done it.
$logger->pushHandler($handler);

$logger->warn('Some message');
```

### CODE REVIEW

**Comment by bradmkjr** [comment]
We may want to consider also deleting the tables on plugin deactivation? Maybe with a variable to check to preserve or delete data on deactivation?

**Comment by Flynsarmy** [comment]
Done. See #4 complete with code example. You should also be able to remove your disclaimer in the readme now https://github.com/bradmkjr/monolog-wordpress#disclaimer.

Once #4 is pulled would it be possible to make a new release? We're eager to get this package included in our plugin.

**Comment by bradmkjr** [comment]
1.5.0 has been pushed, let me know if you need anything else.

**Comment by bradmkjr** [comment]
1.6.0 has been pushed to update composer.json

**Comment by Flynsarmy** [comment]
Thanks!

**Comment by bradmkjr** [comment]
I removed $extraFields, I feel that is duplication of $additionalFields and not referenced anywhere else besides the initiation method.

**Comment by bradmkjr** [comment]
I'm an idiot, should not code before coffee. Reverting last changes, will have a good release for you soon.

**Pull request merged**
