### PR TITLE
Added support to PHP v8.1, Monolog v3.x and Wordpress v6.x

### PR DESCRIPTION
**Pull request by frugan-dev**

### CODE REVIEW

**Comment by BenceSzalai** [comment]
Thanks for taking care of the update. All seems good by the first look, except for the minor thing above.

**Comment by frugan-dev** [comment]
Hi there, if you refer to old commit [28ba9d4](https://github.com/bradmkjr/monolog-wordpress/pull/22/commits/28ba9d4744f655753a0f536302685692a1479729), it was reverted by commit [a7360cb](https://github.com/bradmkjr/monolog-wordpress/pull/22/commits/a7360cb780c60a4bdc947f514e380fb72932d09a)

**Comment by michaelbourne** [comment]
Anything holding this up from merging?

**Comment by bradmkjr** [comment]
> Anything holding this up from merging?

spam filtering on my Gmail account.

**Comment by BenceSzalai** [comment]
I think there is a bug in line 301 in `WordPressHandler.php`. That's why I did not merge it. Is that review only visible to me, or why is that ignored?

**Comment by frugan-dev** [comment]
@BenceSzalai are you referring to [this edit](https://github.com/bradmkjr/monolog-wordpress/commit/282307503e4c644eae88f72e382446fecfdff221?diff=unified#diff-fba1a63b0d782d5ebcdd8b1125d5e33c96747d3406a2847a0aa9e6e1d9cf1946R302)?

`$contentArray['level']` is an integer value, so it is incorrect to pass it to the [`Level::fromName`](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Level.php#L88) method.

To be honest even `Logger::getLevelName($contentArray['level'])` does not seem the right way, because the [`Logger::getLevelName`](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Logger.php#L455) method, even if returning the desired string, is commented by Monolog as follows:

> This still returns a string instead of a Level for BC, but **new code should not rely on this method**.

So maybe this is the right code to use:

```php
Level::fromValue($contentArray['level'])->getName()
```
Waiting for a confirmation..

**Comment by bradmkjr** [comment]
Sorry @BenceSzalai I didn't see you're review comment, it's only visible when I mouse over your avatar.

image

If someone wants to open a issue, I can look into current code base and updated Monolog documenation / best practice and see what we can do to get it inline.

**Comment by BenceSzalai** [comment]
@bradmkjr : Strange. I've opened a review thread back than at the time of the PR. It looks like this:

CleanShot 2023-07-08 at 16 46 38

But nevermind...

I've took another look and I think my initial review could have been wrong, because I've compared the code to Monolog v2 instead of v3.

I'd suggest to keep the main versions in sync, just like I've done with v1 vs v2, because there are some changes in the Monolog API and [to make the same code compatible with both v2 and v3](https://github.com/Seldaek/monolog/blob/main/UPGRADE.md) probably is more complicated than to simply bump the main version and keep them separate. This is because this library can be considered feature complete, so the expected amount of work to backport any new features is minimal anyway. This is also beneficial, because the library doesn't have tests, so changes such as in this PR has a risk of breaking existing usage scenarios.

If you agree I can prepare a new branch and release v3.0.0 for Monolog v3 based on this PR, and keep the v1 and v2 branches as they are today, to keep supporting v1 and v2 for any existing users. 

Let me know if I should proceed with it!

**Comment by BenceSzalai** [comment]
@bradmkjr: I guess the notification went to spam again. Could you take a look at my last question please?

**Pull request merged**
